### ISSUE TITLE
Fails to install node-jre

### ISSUE THREAD

**Issue by mastoj** [schreiben/node-jre#2]
Not sure what is wrong, but it seems like it fails on the download and preparing jre:

Error log:

```
  downloading and preparing JRE [==============================                                                  ] 37% 0.0sstream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:355:17)
npm WARN nodetest@1.0.0 No description
npm WARN nodetest@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "node-jre"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
```

**Comment by kmaillet** [comment]
I'm facing this exact problem. I'm unable to install this package anymore, even though I've been using it for several weeks.

Did you find any fix ? 

Thanks

**Comment by mastoj** [comment]
Yes, I fixed it in the PR, which you can try it by adding as a dependency. But when I used that there was some error of jar's not being loaded. And to work around that I had to create a private repo where I bundled the jre I know works for me in a separate branch and use that when downloading instead of official. Can't share that since I don't want to distribute the jre.

**Comment by kmaillet** [comment]
Thanks @mastoj !
@tilmankamp  could you update the npm package as well ? I think I still get the old version when I npm install. Thanks !

**Comment by tilmankamp** [comment]
@kmaillet-arcane Here you go...

**Comment by mastoj** [comment]
Just so I'm clear. I had some issues with the latest jre, which I couldn't figure out. It seems like some cryptographic packages wasn't loaded as they should have been.

**Comment by kmaillet** [comment]
@mastoj , I'm also having the problem with javax/crypto/SecretKey package from time to time. Did you find a way to solve it? 

Thanks !

**Comment by domparry** [comment]
Same issue here. As @mastof mentions, the solution is to package a private bundled version with a working jre... At least until this is resolved.

**Comment by anthonyraymond** [comment]
It may be related to #6 (not sure)
